# Module manifest for module 'helium'
# Generated by: David Stein
# Generated on: 4/19/2023
# Last updated: 10/10/2025
@{
	RootModule        = '.\helium.psm1'
	ModuleVersion     = '1.2.9'
	# CompatiblePSEditions = @()
	GUID              = '00631599-1008-4991-a1cf-3e793e21cff1'
	Author            = 'Skatterbrainz'
	CompanyName       = 'Brainz be Skattered'
	Copyright         = '(c) 2023-2025 Skatterbrainz. All rights reserved.'
	Description       = 'Assorted Utilities to make your day happier than inhaling a party balloon.'
	PowerShellVersion = '5.1'
	# PowerShellHostName = ''
	# PowerShellHostVersion = ''
	# DotNetFrameworkVersion = ''
	# ClrVersion = ''
	# ProcessorArchitecture = ''
	RequiredModules   = @('psIni')
	# RequiredAssemblies = @()
	# ScriptsToProcess = @()
	# TypesToProcess = @()
	# FormatsToProcess = @()
	# NestedModules = @()
	FunctionsToExport = '*'
	CmdletsToExport   = '*'
	VariablesToExport = '*'
	AliasesToExport   = '*'
	# DscResourcesToExport = @()
	# ModuleList = @()
	# FileList = @()
	PrivateData       = @{
		PSData = @{
			Tags                     = @('helium', 'windows', 'utility', 'skatterbrainz', 'url', 'ldap', 'grep', 'event', 'browser', 'profiles', 'chrome', 'firefox', 'edge', 'resource', 'sed', 'string', 'text', 'wlan', 'network', 'modules', 'linux', 'excel', 'phone')
			LicenseUri               = 'https://github.com/Skatterbrainz/helium/blob/master/LICENSE'
			ProjectUri               = 'https://github.com/Skatterbrainz/helium'
			IconUri                  = 'https://user-images.githubusercontent.com/11505001/233167377-5462ad29-5e4e-4b68-9517-1c472baec287.png'
			# ReleaseNotes = ''
			# Prerelease = ''
			RequireLicenseAcceptance = $false
			# ExternalModuleDependencies = @()
		} # End of PSData hashtable
	} # End of PrivateData hashtable
	# HelpInfoURI = ''
	# DefaultCommandPrefix = ''
}
