# Module manifest for module 'helium'
# Generated by: David Stein
# Generated on: 4/19/2023
# Last updated: 4/19/2023
@{
RootModule = '.\helium.psm1'
ModuleVersion = '1.0.0'
# CompatiblePSEditions = @()
GUID = '00631599-1008-4991-a1cf-3e793e21cff1'
Author = 'David Stein'
CompanyName = 'David Stein'
Copyright = '(c) 2023 David Stein. All rights reserved.'
Description = 'Assorted Utilities to make your day happier than eating a handful of sedatives'
PowerShellVersion = '5.1'
# PowerShellHostName = ''
# PowerShellHostVersion = ''
# DotNetFrameworkVersion = ''
# ClrVersion = ''
# ProcessorArchitecture = ''
# RequiredModules = @()
# RequiredAssemblies = @()
# ScriptsToProcess = @()
# TypesToProcess = @()
# FormatsToProcess = @()
# NestedModules = @()
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
# DscResourcesToExport = @()
# ModuleList = @()
# FileList = @()
PrivateData = @{
    PSData = @{
        Tags = @('helium','windows','utility','skatterbrainz','url','ldap','grep','event','browser','resource')
        LicenseUri = 'https://github.com/Skatterbrainz/helium/blob/master/LICENSE'
        ProjectUri = 'https://github.com/Skatterbrainz/helium'
        # IconUri = ''
        # ReleaseNotes = ''
        # Prerelease = ''
        RequireLicenseAcceptance = $false
        # ExternalModuleDependencies = @()
    } # End of PSData hashtable
} # End of PrivateData hashtable
# HelpInfoURI = ''
# DefaultCommandPrefix = ''
}

